[package]
name = "puzzle_15_solver_v2"
version = "0.1.0"
authors = ["Max Hargreaves <max_hargreaves@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyed_priority_queue = "0.1.3"